name: On push to main branch

on:
  push:
    branches: [main]

jobs:
  MainBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v1
        with:
          project_status: official
          project_stability: experimental
          project_type: other
